services:
  db:
    image: postgres:15-alpine
    container_name: dev-postgres
    environment:
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_db
      LANG: nb_NO.utf8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=nb_NO.utf8"
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
