steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '18'

  - name: Install dependencies
    run: npm ci

  - name: Verify DATABASE_URL is present
    run: echo "DATABASE_URL is set"
    if: env.DATABASE_URL != ''

  - name: Verify JWT_SECRET is present
    run: echo "JWT_SECRET is set"
    if: env.JWT_SECRET != ''

  - name: Build TypeScript
    run: npm run build

  - name: Run tests
    run: npm run test

  - name: Build Docker image
    if: github.ref == 'refs/heads/main'
    run: docker build -t crm-core:latest .