name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installer avhengigheter
        run: pnpm install --frozen-lockfile

      - name: Kjøre linting
        run: pnpm run lint

      - name: Kjøre tester
        run: pnpm run test

      - name: Bygg prosjektet
        run: pnpm run build