name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Sett opp Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer avhengigheter
        run: npm install

      - name: Kjøre linting
        run: npm run lint

      - name: Kjøre tester
        run: npm run test

      - name: Bygg prosjektet
        run: npm run build